
package com.upsud.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-02-04T15:13:44.954+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class WeatherService_WeatherServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.upsud.com/", "WeatherServiceService");

    private WeatherService_WeatherServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WeatherServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WeatherServiceService ss = new WeatherServiceService(wsdlURL, SERVICE_NAME);
        WeatherService port = ss.getWeatherServicePort();  
        
        {
        System.out.println("Invoking getData...");
        java.lang.String _getData_arg0 = "";
        java.lang.String _getData_arg1 = "";
        java.lang.String _getData_arg2 = "";
        com.upsud.ws.Data _getData__return = port.getData(_getData_arg0, _getData_arg1, _getData_arg2);
        System.out.println("getData.result=" + _getData__return);


        }

        System.exit(0);
    }

}
